trigger:
  branches:
    include:
      - master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '9551b013-da60-417c-90ff-80501ddcfa87'
  imageRepository: 'frontend-image'   # (Fixed typo: 'iamge' → 'image')
  containerRegistry: 'pipelinecontainerregistry1.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'agent-pool'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
- stage: Push
  displayName: Push stage
  jobs:
  - job: Push
    steps:
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: |
          $(tag)
          latest
